version: '3.8'

services:
  mlflow:
    build: ./project/mlflow
    command: mlflow server --backend-store-uri postgresql://postgres:postgres@mlflowdb:5432/tracking --default-artifact-root s3://test-repo-wanghuan --host 0.0.0.0 --no-serve-artifacts
    volumes:
      - ./project/mlflow:/usr/src/app
    ports:
      - 10086:5000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:   # new
      - mlflowdb

  mlflowdb:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres